/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package juegocurzarrio;

import javax.swing.JOptionPane;

/**
 *
 * @author Pablo-PC
 */
public class Juego extends javax.swing.JFrame {

    private int mama = 0, hija1 = 0, hija2 = 0, papa = 0, hijo1 = 0, hijo2 = 0, policia = 0, ladron = 0, lan = 0;//Personajes en posicion original
    private String ladoLancha = "";//Lado de la lancha
    private int posicion, posicion2;//Posicion del personaje en la lancha
    private int valor1, valor2, valor3, valor4;//Valores de labels
    private int contador = 0, suma = 0;

    Movimiento mv = new Movimiento();
    Sonido so = new Sonido();
    
    /**
     * Creates new form Juego
     */
    public Juego() {
        initComponents();
        setBounds(100, 0, 1195, 730);
        btn_regresar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblInstrucciones = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbl_Movimientos = new javax.swing.JLabel();
        lbl_hija2 = new javax.swing.JLabel();
        lbl_hija1 = new javax.swing.JLabel();
        lbl_madre = new javax.swing.JLabel();
        lbl_hijo2 = new javax.swing.JLabel();
        lbl_hijo1 = new javax.swing.JLabel();
        lbl_padre = new javax.swing.JLabel();
        lbl_ladron = new javax.swing.JLabel();
        lbl_policia = new javax.swing.JLabel();
        lbl_lancha = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnInstrucciones = new javax.swing.JButton();
        btn_Reiniciar = new javax.swing.JButton();
        btn_regresar = new javax.swing.JButton();
        btn_Avanzar = new javax.swing.JButton();
        lblValor1 = new javax.swing.JLabel();
        lblValor2 = new javax.swing.JLabel();
        lblValor3 = new javax.swing.JLabel();
        lblValor4 = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        lblInstrucciones.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblInstrucciones.setText("Instrucciónes:");
        getContentPane().add(lblInstrucciones);
        lblInstrucciones.setBounds(70, 0, 100, 30);

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel3.setText("Cantidad de movimientos de la lancha:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(780, 20, 270, 14);

        lbl_Movimientos.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbl_Movimientos.setText("0");
        getContentPane().add(lbl_Movimientos);
        lbl_Movimientos.setBounds(1050, 20, 30, 20);

        lbl_hija2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/oveja b.gif"))); // NOI18N
        lbl_hija2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_hija2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_hija2MouseClicked(evt);
            }
        });
        getContentPane().add(lbl_hija2);
        lbl_hija2.setBounds(20, 250, 70, 120);

        lbl_hija1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/oveja n.gif"))); // NOI18N
        lbl_hija1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_hija1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_hija1MouseClicked(evt);
            }
        });
        getContentPane().add(lbl_hija1);
        lbl_hija1.setBounds(110, 250, 65, 120);

        lbl_madre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/granjera.gif"))); // NOI18N
        lbl_madre.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_madre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_madreMouseClicked(evt);
            }
        });
        getContentPane().add(lbl_madre);
        lbl_madre.setBounds(210, 250, 65, 120);

        lbl_hijo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Puerco.gif"))); // NOI18N
        lbl_hijo2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_hijo2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_hijo2MouseClicked(evt);
            }
        });
        getContentPane().add(lbl_hijo2);
        lbl_hijo2.setBounds(20, 380, 70, 110);

        lbl_hijo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Puerco2.gif"))); // NOI18N
        lbl_hijo1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_hijo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_hijo1MouseClicked(evt);
            }
        });
        getContentPane().add(lbl_hijo1);
        lbl_hijo1.setBounds(110, 380, 70, 110);

        lbl_padre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Granjero.gif"))); // NOI18N
        lbl_padre.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_padre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_padreMouseClicked(evt);
            }
        });
        getContentPane().add(lbl_padre);
        lbl_padre.setBounds(205, 380, 65, 120);

        lbl_ladron.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Ladron.gif"))); // NOI18N
        lbl_ladron.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_ladron.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_ladronMouseClicked(evt);
            }
        });
        getContentPane().add(lbl_ladron);
        lbl_ladron.setBounds(50, 510, 70, 130);

        lbl_policia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Policia.gif"))); // NOI18N
        lbl_policia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_policia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_policiaMouseClicked(evt);
            }
        });
        getContentPane().add(lbl_policia);
        lbl_policia.setBounds(140, 510, 60, 135);

        lbl_lancha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/lancha.gif"))); // NOI18N
        getContentPane().add(lbl_lancha);
        lbl_lancha.setBounds(290, 530, 250, 70);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/au.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(70, 30, 50, 40);

        btnInstrucciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ICONO-SONIDO.png"))); // NOI18N
        btnInstrucciones.setBorderPainted(false);
        btnInstrucciones.setContentAreaFilled(false);
        btnInstrucciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInstruccionesActionPerformed(evt);
            }
        });
        getContentPane().add(btnInstrucciones);
        btnInstrucciones.setBounds(20, 30, 50, 40);

        btn_Reiniciar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/reiniciar.jpg"))); // NOI18N
        btn_Reiniciar.setBorderPainted(false);
        btn_Reiniciar.setContentAreaFilled(false);
        btn_Reiniciar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_Reiniciar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/reiniciar2.jpg"))); // NOI18N
        btn_Reiniciar.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/reiniciar.jpg"))); // NOI18N
        btn_Reiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ReiniciarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Reiniciar);
        btn_Reiniciar.setBounds(473, 13, 180, 70);

        btn_regresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Boton2.gif"))); // NOI18N
        btn_regresar.setBorderPainted(false);
        btn_regresar.setContentAreaFilled(false);
        btn_regresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_regresar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Boton2-2.gif"))); // NOI18N
        btn_regresar.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Boton2.gif"))); // NOI18N
        btn_regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_regresarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_regresar);
        btn_regresar.setBounds(900, 603, 60, 60);

        btn_Avanzar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Boton1.gif"))); // NOI18N
        btn_Avanzar.setBorderPainted(false);
        btn_Avanzar.setContentAreaFilled(false);
        btn_Avanzar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_Avanzar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Boton1-2.gif"))); // NOI18N
        btn_Avanzar.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Boton1.gif"))); // NOI18N
        btn_Avanzar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AvanzarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Avanzar);
        btn_Avanzar.setBounds(240, 610, 60, 60);

        lblValor1.setText("0");
        getContentPane().add(lblValor1);
        lblValor1.setBounds(10, 10, 6, 14);

        lblValor2.setText("0");
        getContentPane().add(lblValor2);
        lblValor2.setBounds(20, 10, 6, 14);

        lblValor3.setText("0");
        getContentPane().add(lblValor3);
        lblValor3.setBounds(1106, 10, 20, 14);

        lblValor4.setText("0");
        getContentPane().add(lblValor4);
        lblValor4.setBounds(1160, 10, 6, 14);

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo.png"))); // NOI18N
        getContentPane().add(Fondo);
        Fondo.setBounds(0, 0, 1180, 680);

        jMenu1.setText("Opcion");

        jMenuItem1.setText("Regresar a menu principal");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_AvanzarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AvanzarActionPerformed
        if (mama == 1 || papa == 1 || policia == 1) {
            if ((policia == ladron) || (ladron != mama && ladron != hija1 && ladron != hija2 && ladron != papa && ladron != hijo1 && ladron != hijo2)) {
                if (mama != papa && (mama == hijo1 || mama == hijo2)) {
                    so.sonidoE();
                    JOptionPane.showMessageDialog(null, "La granjera se llevara a los puercos");
                    
                    if(Integer.parseInt(lblValor1.getText())==Integer.parseInt(lblValor2.getText())){
                        lblValor1.setText(Integer.toString(0));
                        lblValor2.setText(Integer.toString(0));
                    }else{
                        lblValor1.setText(Integer.toString(0));
                    }
                    if (papa == 1) {
                        lbl_padre.setBounds(210, 365, 65, 130);
                        add(lbl_padre);
                        papa = 0;
                    }
                    if (hijo1 == 1) {
                        lbl_hijo1.setBounds(110, 365, 65, 130);
                        add(lbl_hijo1);
                        hijo1 = 0;
                    }
                    if (hijo2 == 1) {
                        lbl_hijo2.setBounds(20, 365, 65, 130);
                        add(lbl_hijo2);
                        hijo2 = 0;
                    }
                    if (hija1 == 1) {
                        lbl_hija1.setBounds(110, 235, 65, 130);
                        add(lbl_hija1);
                        hija1 = 0;
                    }
                    if (hija2 == 1) {
                        lbl_hija2.setBounds(20, 235, 65, 130);
                        add(lbl_hija2);
                        hija2 = 0;
                    }
                    if (policia == 1) {
                        lbl_policia.setBounds(140, 490, 65, 130);
                        add(lbl_policia);
                        policia = 0;
                    }
                    if (ladron == 1) {
                        lbl_ladron.setBounds(50, 490, 70, 120);
                        add(lbl_ladron);
                        ladron = 0;
                    }
                } else {
                    if (papa != mama && (papa == hija1 || papa == hija2)) {
                        so.sonidoE();
                        JOptionPane.showMessageDialog(null, "El granjero se llevara a las ovejas");
                        if (Integer.parseInt(lblValor1.getText()) == Integer.parseInt(lblValor2.getText())) {
                            lblValor1.setText(Integer.toString(0));
                            lblValor2.setText(Integer.toString(0));
                        } else {
                            lblValor1.setText(Integer.toString(0));
                        }
                        if (mama == 1) {
                            lbl_madre.setBounds(210, 235, 65, 130);
                            add(lbl_madre);
                            mama = 0;
                        }
                        if (hijo1 == 1) {
                            lbl_hijo1.setBounds(110, 365, 65, 130);
                            add(lbl_hijo1);
                            hijo1 = 0;
                        }
                        if (hijo2 == 1) {
                            lbl_hijo2.setBounds(20, 365, 65, 130);
                            add(lbl_hijo2);
                            hijo2 = 0;
                        }
                        if (hija1 == 1) {
                            lbl_hija1.setBounds(110, 235, 65, 130);
                            add(lbl_hija1);
                            hija1 = 0;
                        }
                        if (hija2 == 1) {
                            lbl_hija2.setBounds(20, 235, 65, 130);
                            add(lbl_hija2);
                            hija2 = 0;
                        }
                        if (policia == 1) {
                            lbl_policia.setBounds(140, 490, 65, 130);
                            add(lbl_policia);
                            policia = 0;
                        }
                        if (ladron == 1) {
                            lbl_ladron.setBounds(50, 490, 70, 120);
                            add(lbl_ladron);
                            ladron = 0;
                        }
                    } else {
                        if ((mama == 0 && (hija1 == 2 && hija2 == 2)) && papa == 1) {
                            so.sonidoE();
                            JOptionPane.showMessageDialog(null, "El granjero se llevara a las ovejas");
                            if (Integer.parseInt(lblValor1.getText()) == Integer.parseInt(lblValor2.getText())) {
                                lblValor1.setText(Integer.toString(0));
                                lblValor2.setText(Integer.toString(0));
                            } else {
                                lblValor1.setText(Integer.toString(0));
                            }
                            if (papa == 1) {
                                lbl_padre.setBounds(210, 365, 65, 130);
                                add(lbl_padre);
                                papa = 0;
                            }
                            if (hijo1 == 1) {
                                lbl_hijo1.setBounds(110, 365, 65, 130);
                                add(lbl_hijo1);
                                hijo1 = 0;
                            }
                            if (hijo2 == 1) {
                                lbl_hijo2.setBounds(20, 365, 65, 130);
                                add(lbl_hijo2);
                                hijo2 = 0;
                            }
                            if (policia == 1) {
                                lbl_policia.setBounds(140, 490, 65, 130);
                                add(lbl_policia);
                                policia = 0;
                            }
                            if (ladron == 1) {
                                lbl_ladron.setBounds(50, 490, 70, 120);
                                add(lbl_ladron);
                                ladron = 0;
                            }
                        } else {
                            if ((papa == 0 && (hijo1 == 2 && hijo2 == 2)) && mama == 1) {
                                so.sonidoE();
                                JOptionPane.showMessageDialog(null, "La granjera se llevara a los puercos");
                                if (Integer.parseInt(lblValor1.getText()) == Integer.parseInt(lblValor2.getText())) {
                                    lblValor1.setText(Integer.toString(0));
                                    lblValor2.setText(Integer.toString(0));
                                } else {
                                    lblValor1.setText(Integer.toString(0));
                                }
                                if (mama == 1) {
                                    lbl_madre.setBounds(210, 235, 65, 130);
                                    add(lbl_madre);
                                    mama = 0;
                                }
                                if (hija1 == 1) {
                                    lbl_hija1.setBounds(110, 235, 65, 130);
                                    add(lbl_hija1);
                                    hija1 = 0;
                                }
                                if (hija2 == 1) {
                                    lbl_hija2.setBounds(20, 235, 65, 130);
                                    add(lbl_hija2);
                                    hija2 = 0;
                                }
                                if (policia == 1) {
                                    lbl_policia.setBounds(140, 490, 65, 130);
                                    add(lbl_policia);
                                    policia = 0;
                                }
                                if (ladron == 1) {
                                    lbl_ladron.setBounds(50, 490, 70, 120);
                                    add(lbl_ladron);
                                    ladron = 0;
                                }
                            } else {
                                if (ladron == 2 && mama == 1 && hija1 == 0 && hija2 == 0 && papa == 1 && hijo1 == 0 && hijo2 == 0 && policia == 0) {
                                    so.sonidoE();
                                    JOptionPane.showMessageDialog(null, "Ladron le roba a los granjeros");
                                    if (Integer.parseInt(lblValor1.getText()) == Integer.parseInt(lblValor2.getText())) {
                                        lblValor1.setText(Integer.toString(0));
                                        lblValor2.setText(Integer.toString(0));
                                    } else {
                                        lblValor1.setText(Integer.toString(0));
                                    }
                                    if (mama == 1) {
                                        lbl_madre.setBounds(210, 235, 65, 130);
                                        add(lbl_madre);
                                        mama = 0;
                                    }
                                    if (hijo1 == 1) {
                                        lbl_hijo1.setBounds(110, 365, 65, 130);
                                        add(lbl_hijo1);
                                        hijo1 = 0;
                                    }
                                    if (hijo2 == 1) {
                                        lbl_hijo2.setBounds(20, 365, 65, 130);
                                        add(lbl_hijo2);
                                        hijo2 = 0;
                                    }
                                    if (hija1 == 1) {
                                        lbl_hija1.setBounds(110, 235, 65, 130);
                                        add(lbl_hija1);
                                        hija1 = 0;
                                    }
                                    if (hija2 == 1) {
                                        lbl_hija2.setBounds(20, 235, 65, 130);
                                        add(lbl_hija2);
                                        hija2 = 0;
                                    }
                                    if (policia == 1) {
                                        lbl_policia.setBounds(140, 490, 65, 130);
                                        add(lbl_policia);
                                        policia = 0;
                                    }
                                    if (papa == 1) {
                                        lbl_padre.setBounds(210, 365, 65, 130);
                                        add(lbl_padre);
                                        papa = 0;
                                    }
                                } else {
                                    lbl_lancha.setBounds(580, 520, 260, 70);
                                    add(lbl_lancha);
                                    lan = 1;

                                    if (mama == 1) {
                                        lbl_madre.setBounds(880, 235, 65, 130);
                                        add(lbl_madre);
                                        mama = 2;
                                    }

                                    if (hija1 == 1) {
                                        lbl_hija1.setBounds(980, 235, 65, 130);
                                        add(lbl_hija1);
                                        hija1 = 2;
                                    }

                                    if (hija2 == 1) {
                                        lbl_hija2.setBounds(1080, 235, 65, 130);
                                        add(lbl_hija2);
                                        hija2 = 2;
                                    }

                                    if (papa == 1) {
                                        lbl_padre.setBounds(880, 365, 65, 130);
                                        add(lbl_padre);
                                        papa = 2;
                                    }

                                    if (hijo1 == 1) {
                                        lbl_hijo1.setBounds(980, 365, 65, 130);
                                        add(lbl_hijo1);
                                        hijo1 = 2;
                                    }

                                    if (hijo2 == 1) {
                                        lbl_hijo2.setBounds(1080, 365, 65, 130);
                                        add(lbl_hijo2);
                                        hijo2 = 2;
                                    }

                                    if (policia == 1) {
                                        lbl_policia.setBounds(950, 490, 65, 130);
                                        add(lbl_policia);
                                        policia = 2;
                                    }

                                    if (ladron == 1) {
                                        lbl_ladron.setBounds(1050, 490, 70, 130);
                                        add(lbl_ladron);
                                        ladron = 2;
                                    }
                                    btn_Avanzar.setEnabled(false);
                                    btn_regresar.setEnabled(true);
                                    lblValor1.setText(Integer.toString(0));
                                    lblValor2.setText(Integer.toString(0));
                                }
                            }
                        }
                    }
                }
            } else {
                so.sonidoE();
                JOptionPane.showMessageDialog(null, "El ladron puede robar");
                if (Integer.parseInt(lblValor1.getText()) == Integer.parseInt(lblValor2.getText())) {
                    lblValor1.setText(Integer.toString(0));
                    lblValor2.setText(Integer.toString(0));
                } else {
                    lblValor1.setText(Integer.toString(0));
                }
                if (mama == 1) {
                    lbl_madre.setBounds(210, 235, 65, 130);
                    add(lbl_madre);
                    mama = 0;
                }
                if (hijo1 == 1) {
                    lbl_hijo1.setBounds(110, 365, 65, 130);
                    add(lbl_hijo1);
                    hijo1 = 0;
                }
                if (hijo2 == 1) {
                    lbl_hijo2.setBounds(20, 365, 65, 130);
                    add(lbl_hijo2);
                    hijo2 = 0;
                }
                if (hija1 == 1) {
                    lbl_hija1.setBounds(110, 235, 65, 130);
                    add(lbl_hija1);
                    hija1 = 0;
                }
                if (hija2 == 1) {
                    lbl_hija2.setBounds(20, 235, 65, 130);
                    add(lbl_hija2);
                    hija2 = 0;
                }
                if (policia == 1) {
                    lbl_policia.setBounds(140, 490, 65, 130);
                    add(lbl_policia);
                    policia = 0;
                }
                if (papa == 1) {
                    lbl_padre.setBounds(210, 365, 65, 130);
                    add(lbl_padre);
                    papa = 0;
                }
            }
        } else {
            //JOptionPane.showMessageDialog(null, "Porfavor selecciona a un personaje para la lancha", "", JOptionPane.INFORMATION_MESSAGE);
        }
        contador = Integer.parseInt(lbl_Movimientos.getText());
        suma = contador + 1;
        lbl_Movimientos.setText(Integer.toString(suma));

        Fondo.setLocation(0, 0);
        add(Fondo);
        int sumando;
        sumando = contador + 1;
        if (mama == 2 && hija1 == 2 && hija2 == 2 && papa == 2 && hijo1 == 2 && hijo2 == 2 && policia == 2 && ladron == 2) {
            so.sonidoGanar();
            JOptionPane.showMessageDialog(null, "Ganaste!! y tus movimientos fueron " + sumando);
            btn_regresar.setEnabled(false);
        }
    }//GEN-LAST:event_btn_AvanzarActionPerformed

    private void btn_regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_regresarActionPerformed
        if (mama == 3 || papa == 3 || policia == 3) {
            if ((policia == ladron) || (ladron != mama && ladron != hija1 && ladron != hija2 && ladron != papa && ladron != hijo1 && ladron != hijo2)) {
                if (mama != papa && (mama == hijo1 || mama == hijo2)) {
                    so.sonidoE();
                    JOptionPane.showMessageDialog(null, "La granjera se llevara a los puercos");
                    if(Integer.parseInt(lblValor1.getText())==Integer.parseInt(lblValor2.getText())){
                        lblValor3.setText(Integer.toString(0));
                        lblValor4.setText(Integer.toString(0));
                    }else{
                        lblValor3.setText(Integer.toString(0));
                    }
                    if (papa == 3) {
                        lbl_padre.setBounds(880, 365, 65, 130);
                        add(lbl_padre);
                        papa = 2;
                    }
                    if (hijo1 == 3) {
                        lbl_hijo1.setBounds(980, 365, 65, 130);
                        add(lbl_hijo1);
                        hijo1 = 2;
                    }
                    if (hijo2 == 3) {
                        lbl_hijo2.setBounds(1080, 365, 65, 130);
                        add(lbl_hijo2);
                        hijo2 = 2;
                    }
                    if (hija1 == 3) {
                        lbl_hija1.setBounds(980, 235, 65, 130);
                        add(lbl_hija1);
                        hija1 = 2;
                    }
                    if (hija2 == 3) {
                        lbl_hija2.setBounds(1080, 235, 65, 130);
                        add(lbl_hija2);
                        hija2 = 2;
                    }
                    if (policia == 3) {
                        lbl_policia.setBounds(950, 490, 65, 130);
                        add(lbl_policia);
                        policia = 2;
                    }
                    if (ladron == 3) {
                        lbl_ladron.setBounds(1050, 490, 70, 130);
                        add(lbl_ladron);
                        ladron = 2;
                    }
                } else {
                    if (papa != mama && (papa == hija1 || papa == hija2)) {
                        so.sonidoE();
                        JOptionPane.showMessageDialog(null, "El granjero se llevara a las ovejas");
                        if (Integer.parseInt(lblValor1.getText()) == Integer.parseInt(lblValor2.getText())) {
                            lblValor3.setText(Integer.toString(0));
                            lblValor4.setText(Integer.toString(0));
                        } else {
                            lblValor3.setText(Integer.toString(0));
                        }
                        if (mama == 3) {
                            lbl_madre.setBounds(880, 235, 65, 130);
                            add(lbl_madre);
                            mama = 2;
                        }
                        if (hijo1 == 3) {
                            lbl_hijo1.setBounds(980, 365, 65, 130);
                            add(lbl_hijo1);
                            hijo1 = 2;
                        }
                        if (hijo2 == 3) {
                            lbl_hijo2.setBounds(1080, 365, 65, 130);
                            add(lbl_hijo2);
                            hijo2 = 2;
                        }
                        if (hija1 == 3) {
                            lbl_hija1.setBounds(980, 235, 65, 130);
                            add(lbl_hija1);
                            hija1 = 2;
                        }
                        if (hija2 == 3) {
                            lbl_hija2.setBounds(1080, 235, 65, 130);
                            add(lbl_hija2);
                            hija2 = 2;
                        }
                        if (policia == 3) {
                            lbl_policia.setBounds(950, 490, 65, 130);
                            add(lbl_policia);
                            policia = 2;
                        }
                        if (ladron == 3) {
                            lbl_ladron.setBounds(1050, 490, 70, 130);
                            add(lbl_ladron);
                            ladron = 2;
                        }
                    } else {
                        if ((mama == 2 && (hija1 == 0 && hija2 == 0)) && papa == 3) {
                            so.sonidoE();
                            JOptionPane.showMessageDialog(null, "El granjero se llevara a las ovejas");
                            if (Integer.parseInt(lblValor1.getText()) == Integer.parseInt(lblValor2.getText())) {
                                lblValor3.setText(Integer.toString(0));
                                lblValor4.setText(Integer.toString(0));
                            } else {
                                lblValor3.setText(Integer.toString(0));
                            }
                            if (papa == 3) {
                                lbl_padre.setBounds(880, 365, 65, 130);
                                add(lbl_padre);
                                papa = 2;
                            }
                            if (hijo1 == 3) {
                                lbl_hijo1.setBounds(980, 365, 65, 130);
                                add(lbl_hijo1);
                                hijo1 = 2;
                            }
                            if (hijo2 == 3) {
                                lbl_hijo2.setBounds(1080, 365, 65, 130);
                                add(lbl_hijo2);
                                hijo2 = 2;
                            }
                            if (policia == 3) {
                                lbl_policia.setBounds(950, 490, 65, 130);
                                add(lbl_policia);
                                policia = 2;
                            }
                            if (ladron == 3) {
                                lbl_ladron.setBounds(1050, 490, 70, 130);
                                add(lbl_ladron);
                                ladron = 2;
                            }
                        } else {
                            if ((papa == 2 && (hijo1 == 0 && hijo2 == 0)) && mama == 3) {
                                so.sonidoE();
                                JOptionPane.showMessageDialog(null, "La granjera se llevara a los puercos");
                                if (Integer.parseInt(lblValor1.getText()) == Integer.parseInt(lblValor2.getText())) {
                                    lblValor3.setText(Integer.toString(0));
                                    lblValor4.setText(Integer.toString(0));
                                } else {
                                    lblValor3.setText(Integer.toString(0));
                                }
                                if (mama == 3) {
                                    lbl_madre.setBounds(880, 235, 65, 130);
                                    add(lbl_madre);
                                    mama = 2;
                                }
                                if (hija1 == 3) {
                                    lbl_hija1.setBounds(980, 235, 65, 130);
                                    add(lbl_hija1);
                                    hija1 = 2;
                                }
                                if (hija2 == 3) {
                                    lbl_hija2.setBounds(1080, 235, 65, 130);
                                    add(lbl_hija2);
                                    hija2 = 2;
                                }
                                if (policia == 3) {
                                    lbl_policia.setBounds(950, 490, 65, 130);
                                    add(lbl_policia);
                                    policia = 2;
                                }
                                if (ladron == 3) {
                                    lbl_ladron.setBounds(1050, 490, 70, 130);
                                    add(lbl_ladron);
                                    ladron = 2;
                                }
                            } else {
                                if (ladron == 0 && mama == 3 && hija1 == 2 && hija2 == 2 && papa == 3 && hijo1 == 2 && hijo2 == 2 && policia == 2) {
                                    so.sonidoE();
                                    JOptionPane.showMessageDialog(null, "Ladron le roba a los granjeros");
                                    if (Integer.parseInt(lblValor1.getText()) == Integer.parseInt(lblValor2.getText())) {
                                        lblValor3.setText(Integer.toString(0));
                                        lblValor4.setText(Integer.toString(0));
                                    } else {
                                        lblValor3.setText(Integer.toString(0));
                                    }
                                    if (mama == 3) {
                                        lbl_madre.setBounds(880, 235, 65, 130);
                                        add(lbl_madre);
                                        mama = 2;
                                    }
                                    if (hijo1 == 3) {
                                        lbl_hijo1.setBounds(980, 365, 65, 130);
                                        add(lbl_hijo1);
                                        hijo1 = 2;
                                    }
                                    if (hijo2 == 3) {
                                        lbl_hijo2.setBounds(1080, 365, 65, 130);
                                        add(lbl_hijo2);
                                        hijo2 = 2;
                                    }
                                    if (hija1 == 3) {
                                        lbl_hija1.setBounds(980, 235, 65, 130);
                                        add(lbl_hija1);
                                        hija1 = 2;
                                    }
                                    if (hija2 == 3) {
                                        lbl_hija2.setBounds(1080, 235, 65, 130);
                                        add(lbl_hija2);
                                        hija2 = 2;
                                    }
                                    if (policia == 3) {
                                        lbl_policia.setBounds(950, 490, 65, 130);
                                        add(lbl_policia);
                                        policia = 2;
                                    }
                                    if (papa == 3) {
                                        lbl_padre.setBounds(880, 365, 65, 130);
                                        add(lbl_padre);
                                        papa = 2;
                                    }//////////////77
                                } else {
                                    lbl_lancha.setBounds(290, 520, 260, 70);
                                    add(lbl_lancha);
                                    lan = 0;

                                    if (mama == 3) {
                                        lbl_madre.setBounds(210, 235, 65, 130);
                                        add(lbl_madre);
                                        mama = 0;
                                    }

                                    if (hija1 == 3) {
                                        lbl_hija1.setBounds(110, 235, 65, 130);
                                        add(lbl_hija1);
                                        hija1 = 0;
                                    }

                                    if (hija2 == 3) {
                                        lbl_hija2.setBounds(20, 235, 65, 130);
                                        add(lbl_hija2);
                                        hija2 = 0;
                                    }

                                    if (papa == 3) {
                                        lbl_padre.setBounds(210, 365, 65, 130);
                                        add(lbl_padre);
                                        papa = 0;
                                    }

                                    if (hijo1 == 3) {
                                        lbl_hijo1.setBounds(110, 365, 65, 130);
                                        add(lbl_hijo1);
                                        hijo1 = 0;
                                    }

                                    if (hijo2 == 3) {
                                        lbl_hijo2.setBounds(20, 365, 65, 130);
                                        add(lbl_hijo2);
                                        hijo2 = 0;
                                    }

                                    if (policia == 3) {
                                        lbl_policia.setBounds(140, 490, 65, 130);
                                        add(lbl_policia);
                                        policia = 0;
                                    }

                                    if (ladron == 3) {
                                        lbl_ladron.setBounds(50, 490, 70, 120);
                                        add(lbl_ladron);
                                        ladron = 0;
                                    }
                                    btn_Avanzar.setEnabled(true);
                                    btn_regresar.setEnabled(false);
                                    lblValor3.setText(Integer.toString(0));
                                    lblValor4.setText(Integer.toString(0));
                                }
                            }
                        }
                    }
                }
            } else {
                so.sonidoE();
                JOptionPane.showMessageDialog(null, "El ladron puede roba");
                if (Integer.parseInt(lblValor1.getText()) == Integer.parseInt(lblValor2.getText())) {
                    lblValor3.setText(Integer.toString(0));
                    lblValor4.setText(Integer.toString(0));
                } else {
                    lblValor3.setText(Integer.toString(0));
                }
                if (mama == 3) {
                    lbl_madre.setBounds(880, 235, 65, 130);
                    add(lbl_madre);
                    mama = 2;
                }
                if (hijo1 == 3) {
                    lbl_hijo1.setBounds(980, 365, 65, 130);
                    add(lbl_hijo1);
                    hijo1 = 2;
                }
                if (hijo2 == 3) {
                    lbl_hijo2.setBounds(1080, 365, 65, 130);
                    add(lbl_hijo2);
                    hijo2 = 2;
                }
                if (hija1 == 3) {
                    lbl_hija1.setBounds(980, 235, 65, 130);
                    add(lbl_hija1);
                    hija1 = 2;
                }
                if (hija2 == 3) {
                    lbl_hija2.setBounds(1080, 235, 65, 130);
                    add(lbl_hija2);
                    hija2 = 2;
                }
                if (policia == 3) {
                    lbl_policia.setBounds(950, 490, 65, 130);
                    add(lbl_policia);
                    policia = 2;
                }
                if (papa == 3) {
                    lbl_padre.setBounds(880, 365, 65, 130);
                    add(lbl_padre);
                    papa = 2;
                }
            }
        } else {
            //JOptionPane.showMessageDialog(null, "Porfavor selecciona a un personaje para la lancha", "", JOptionPane.INFORMATION_MESSAGE);
        }
        Fondo.setLocation(0, 0);
        add(Fondo);
        contador = Integer.parseInt(lbl_Movimientos.getText());
        suma = contador + 1;
        lbl_Movimientos.setText(Integer.toString(suma));
    }//GEN-LAST:event_btn_regresarActionPerformed

    private void lbl_madreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_madreMouseClicked
        valor1 = Integer.parseInt(lblValor1.getText());
        valor2 = Integer.parseInt(lblValor2.getText());
        valor3 = Integer.parseInt(lblValor3.getText());
        valor4 = Integer.parseInt(lblValor4.getText());
        posicion = mv.ValidacionSalida(valor1, valor2, mama, ladoLancha);
        posicion2 = mv.ValidacionRegreso(valor3, valor4, mama, ladoLancha);
        so.sonidoM();

        if (mama == 0 || mama == 1) {
            if (lan != 0) {
            } else {
                if (posicion == 1) {
                    lblValor1.setText(Integer.toString(1));
                    lbl_madre.setBounds(330, 450, 65, 130);
                    add(lbl_madre);
                    mama = 1;
                    ladoLancha = "arriba";
                } else {
                    if (posicion == 2) {
                        lblValor2.setText(Integer.toString(1));
                        lbl_madre.setBounds(420, 450, 65, 130);
                        add(lbl_madre);
                        mama = 1;
                        ladoLancha = "abajo";
                    } else {
                        if (posicion == 3) {
                            lblValor1.setText(Integer.toString(1));
                            lbl_madre.setBounds(330, 450, 65, 130);
                            add(lbl_madre);
                            mama = 1;
                            ladoLancha = "arriba";
                        } else {
                            if (posicion == 4) {
                                lblValor1.setText(Integer.toString(0));
                                lbl_madre.setBounds(210, 235, 65, 130);
                                add(lbl_madre);
                                mama = 0;
                            } else {
                                if (posicion == 5) {
                                    lblValor2.setText(Integer.toString(0));
                                    lbl_madre.setBounds(210, 235, 65, 130);
                                    add(lbl_madre);
                                    mama = 0;
                                } else {
                                    if (posicion == 6) {
                                        lblValor1.setText(Integer.toString(0));
                                        lbl_madre.setBounds(210, 235, 65, 130);
                                        add(lbl_madre);
                                        mama = 0;
                                    } else {
                                        if (posicion == 7) {
                                            lblValor2.setText(Integer.toString(0));
                                            lbl_madre.setBounds(210, 235, 65, 130);
                                            add(lbl_madre);
                                            mama = 0;
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        } else {
            if (lan != 1) {
            } else {
                if (mama == 2 || mama == 3) {
                    if (posicion2 == 1) {
                        lblValor3.setText(Integer.toString(1));
                        lbl_madre.setBounds(720, 450, 65, 130);
                        add(lbl_madre);
                        mama = 3;
                        ladoLancha = "arriba";
                    } else {
                        if (posicion2 == 2) {
                            lblValor4.setText(Integer.toString(1));
                            lbl_madre.setBounds(630, 450, 70, 130);
                            add(lbl_madre);
                            mama = 3;
                            ladoLancha = "abajo";
                        } else {
                            if (posicion2 == 3) {
                                lblValor3.setText(Integer.toString(1));
                                lbl_madre.setBounds(720, 450, 65, 130);
                                add(lbl_madre);
                                mama = 3;
                                ladoLancha = "arriba";
                            } else {
                                if (posicion2 == 4) {
                                    lblValor3.setText(Integer.toString(0));
                                    lbl_madre.setBounds(880, 235, 65, 130);
                                    add(lbl_madre);
                                    mama = 2;
                                } else {
                                    if (posicion2 == 5) {
                                        lblValor4.setText(Integer.toString(0));
                                        lbl_madre.setBounds(880, 235, 65, 130);
                                        add(lbl_madre);
                                        mama = 2;
                                    } else {
                                        if (posicion2 == 6) {
                                            lblValor3.setText(Integer.toString(0));
                                            lbl_madre.setBounds(880, 235, 65, 130);
                                            add(lbl_madre);
                                            mama = 2;
                                        } else {
                                            if (posicion2 == 7) {
                                                lblValor4.setText(Integer.toString(0));
                                                lbl_madre.setBounds(880, 235, 65, 130);
                                                add(lbl_madre);
                                                mama = 2;
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
        Fondo.setLocation(0, 0);
        add(Fondo);
    }//GEN-LAST:event_lbl_madreMouseClicked

    private void lbl_hija1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_hija1MouseClicked
        valor1 = Integer.parseInt(lblValor1.getText());
        valor2 = Integer.parseInt(lblValor2.getText());
        valor3 = Integer.parseInt(lblValor3.getText());
        valor4 = Integer.parseInt(lblValor4.getText());
        posicion = mv.ValidacionSalida(valor1, valor2, hija1, ladoLancha);
        posicion2 = mv.ValidacionRegreso(valor3, valor4, hija1, ladoLancha);
        so.sonidoM();

        if (hija1 == 0 || hija1 == 1) {
            if (lan != 0) {
            } else {
                if (posicion == 1) {
                    lblValor1.setText(Integer.toString(1));
                    lbl_hija1.setBounds(330, 450, 65, 130);
                    add(lbl_hija1);
                    hija1 = 1;
                    ladoLancha = "arriba";
                } else {
                    if (posicion == 2) {
                        lblValor2.setText(Integer.toString(1));
                        lbl_hija1.setBounds(420, 450, 65, 130);
                        add(lbl_hija1);
                        hija1 = 1;
                        ladoLancha = "abajo";
                    } else {
                        if (posicion == 3) {
                            lblValor1.setText(Integer.toString(1));
                            lbl_hija1.setBounds(330, 450, 65, 130);
                            add(lbl_hija1);
                            hija1 = 1;
                            ladoLancha = "arriba";
                        } else {
                            if (posicion == 4) {
                                lblValor1.setText(Integer.toString(0));
                                lbl_hija1.setBounds(110, 235, 65, 130);
                                add(lbl_hija1);
                                hija1 = 0;
                            } else {
                                if (posicion == 5) {
                                    lblValor2.setText(Integer.toString(0));
                                    lbl_hija1.setBounds(110, 235, 65, 130);
                                    add(lbl_hija1);
                                    hija1 = 0;
                                } else {
                                    if (posicion == 6) {
                                        lblValor1.setText(Integer.toString(0));
                                        lbl_hija1.setBounds(110, 235, 65, 130);
                                        add(lbl_hija1);
                                        hija1 = 0;
                                    } else {
                                        if (posicion == 7) {
                                            lblValor2.setText(Integer.toString(0));
                                            lbl_hija1.setBounds(110, 235, 65, 130);
                                            add(lbl_hija1);
                                            hija1 = 0;
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        } else {
            if (hija1 == 2 || hija1 == 3) {
                if (lan != 1) {
                } else {
                    if (posicion2 == 1) {
                        lblValor3.setText(Integer.toString(1));
                        lbl_hija1.setBounds(720, 450, 70, 130);
                        add(lbl_hija1);
                        hija1 = 3;
                        ladoLancha = "arriba";
                    } else {
                        if (posicion2 == 2) {
                            lblValor4.setText(Integer.toString(1));
                            lbl_hija1.setBounds(630, 450, 70, 130);
                            add(lbl_hija1);
                            hija1 = 3;
                            ladoLancha = "abajo";
                        } else {
                            if (posicion2 == 3) {
                                lblValor3.setText(Integer.toString(1));
                                lbl_hija1.setBounds(720, 450, 70, 130);
                                add(lbl_hija1);
                                hija1 = 3;
                                ladoLancha = "arriba";
                            } else {
                                if (posicion2 == 4) {
                                    lblValor3.setText(Integer.toString(0));
                                    lbl_hija1.setBounds(980, 235, 70, 130);
                                    add(lbl_hija1);
                                    hija1 = 2;
                                } else {
                                    if (posicion2 == 5) {
                                        lblValor4.setText(Integer.toString(0));
                                        lbl_hija1.setBounds(980, 235, 70, 130);
                                        add(lbl_hija1);
                                        hija1 = 2;
                                    } else {
                                        if (posicion2 == 6) {
                                            lblValor3.setText(Integer.toString(0));
                                            lbl_hija1.setBounds(980, 235, 70, 130);
                                            add(lbl_hija1);
                                            hija1 = 2;
                                        } else {
                                            if (posicion2 == 7) {
                                                lblValor4.setText(Integer.toString(0));
                                                lbl_hija1.setBounds(980, 235, 70, 130);
                                                add(lbl_hija1);
                                                hija1 = 2;
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
        Fondo.setLocation(0, 0);
        add(Fondo);
    }//GEN-LAST:event_lbl_hija1MouseClicked

    private void lbl_hija2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_hija2MouseClicked
        valor1 = Integer.parseInt(lblValor1.getText());
        valor2 = Integer.parseInt(lblValor2.getText());
        valor3 = Integer.parseInt(lblValor3.getText());
        valor4 = Integer.parseInt(lblValor4.getText());
        posicion = mv.ValidacionSalida(valor1, valor2, hija2, ladoLancha);
        posicion2 = mv.ValidacionRegreso(valor3, valor4, hija2, ladoLancha);
        so.sonidoM();

        if (hija2 == 0 || hija2 == 1) {
            if (lan != 0) {
            } else {
                if (posicion == 1) {
                    lblValor1.setText(Integer.toString(1));
                    lbl_hija2.setBounds(330, 450, 70, 130);
                    add(lbl_hija2);
                    hija2 = 1;
                    ladoLancha = "arriba";
                } else {
                    if (posicion == 2) {
                        lblValor2.setText(Integer.toString(1));
                        lbl_hija2.setBounds(420, 450, 70, 130);
                        add(lbl_hija2);
                        hija2 = 1;
                        ladoLancha = "abajo";
                    } else {
                        if (posicion == 3) {
                            lblValor1.setText(Integer.toString(1));
                            lbl_hija2.setBounds(330, 450, 70, 130);
                            add(lbl_hija2);
                            hija2 = 1;
                            ladoLancha = "arriba";
                        } else {
                            if (posicion == 4) {
                                lblValor1.setText(Integer.toString(0));
                                lbl_hija2.setBounds(20, 235, 70, 130);
                                add(lbl_hija2);
                                hija2 = 0;
                            } else {
                                if (posicion == 5) {
                                    lblValor2.setText(Integer.toString(0));
                                    lbl_hija2.setBounds(20, 235, 70, 130);
                                    add(lbl_hija2);
                                    hija2 = 0;
                                } else {
                                    if (posicion == 6) {
                                        lblValor1.setText(Integer.toString(0));
                                        lbl_hija2.setBounds(20, 235, 70, 130);
                                        add(lbl_hija2);
                                        hija2 = 0;
                                    } else {
                                        if (posicion == 7) {
                                            lblValor2.setText(Integer.toString(0));
                                            lbl_hija2.setBounds(20, 235, 70, 130);
                                            add(lbl_hija2);
                                            hija2 = 0;
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        } else {
            if (hija2 == 2 || hija2 == 3) {
                if (lan != 1) {
                } else {
                    if (posicion2 == 1) {
                        lblValor3.setText(Integer.toString(1));
                        lbl_hija2.setBounds(720, 450, 70, 130);
                        add(lbl_hija2);
                        hija2 = 3;
                        ladoLancha = "arriba";
                    } else {
                        if (posicion2 == 2) {
                            lblValor4.setText(Integer.toString(1));
                            lbl_hija2.setBounds(630, 450, 70, 130);
                            add(lbl_hija2);
                            hija2 = 3;
                            ladoLancha = "abajo";
                        } else {
                            if (posicion2 == 3) {
                                lblValor3.setText(Integer.toString(1));
                                lbl_hija2.setBounds(720, 450, 70, 130);
                                add(lbl_hija2);
                                hija2 = 3;
                                ladoLancha = "arriba";
                            } else {
                                if (posicion2 == 4) {
                                    lblValor3.setText(Integer.toString(0));
                                    lbl_hija2.setBounds(1080, 235, 70, 130);
                                    add(lbl_hija2);
                                    hija2 = 2;
                                } else {
                                    if (posicion2 == 5) {
                                        lblValor4.setText(Integer.toString(0));
                                        lbl_hija2.setBounds(1080, 235, 70, 130);
                                        add(lbl_hija2);
                                        hija2 = 2;
                                    } else {
                                        if (posicion2 == 6) {
                                            lblValor3.setText(Integer.toString(0));
                                            lbl_hija2.setBounds(1080, 235, 70, 130);
                                            add(lbl_hija2);
                                            hija2 = 2;
                                        } else {
                                            if (posicion2 == 7) {
                                                lblValor4.setText(Integer.toString(0));
                                                lbl_hija2.setBounds(1080, 235, 70, 130);
                                                add(lbl_hija2);
                                                hija2 = 2;
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
        Fondo.setLocation(0, 0);
        add(Fondo);
    }//GEN-LAST:event_lbl_hija2MouseClicked

    private void lbl_padreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_padreMouseClicked
        valor1 = Integer.parseInt(lblValor1.getText());
        valor2 = Integer.parseInt(lblValor2.getText());
        valor3 = Integer.parseInt(lblValor3.getText());
        valor4 = Integer.parseInt(lblValor4.getText());
        posicion = mv.ValidacionSalida(valor1, valor2, papa, ladoLancha);
        posicion2 = mv.ValidacionRegreso(valor3, valor4, papa, ladoLancha);
        so.sonidoM();

        if (papa == 0 || papa == 1) {
            if (lan != 0) {
            } else {
                if (posicion == 1) {
                    lblValor1.setText(Integer.toString(1));
                    lbl_padre.setBounds(330, 450, 70, 130);
                    add(lbl_padre);
                    papa = 1;
                    ladoLancha = "arriba";
                } else {
                    if (posicion == 2) {
                        lblValor2.setText(Integer.toString(1));
                        lbl_padre.setBounds(420, 450, 70, 130);
                        add(lbl_padre);
                        papa = 1;
                        ladoLancha = "abajo";
                    } else {
                        if (posicion == 3) {
                            lblValor1.setText(Integer.toString(1));
                            lbl_padre.setBounds(330, 450, 70, 130);
                            add(lbl_padre);
                            papa = 1;
                            ladoLancha = "arriba";
                        } else {
                            if (posicion == 4) {
                                lblValor1.setText(Integer.toString(0));
                                lbl_padre.setBounds(210, 365, 70, 130);
                                add(lbl_padre);
                                papa = 0;
                            } else {
                                if (posicion == 5) {
                                    lblValor2.setText(Integer.toString(0));
                                    lbl_padre.setBounds(210, 365, 70, 130);
                                    add(lbl_padre);
                                    papa = 0;
                                } else {
                                    if (posicion == 6) {
                                        lblValor1.setText(Integer.toString(0));
                                        lbl_padre.setBounds(210, 365, 70, 130);
                                        add(lbl_padre);
                                        papa = 0;
                                    } else {
                                        if (posicion == 7) {
                                            lblValor2.setText(Integer.toString(0));
                                            lbl_padre.setBounds(210, 365, 70, 130);
                                            add(lbl_padre);
                                            papa = 0;
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        } else {
            if (papa == 2 || papa == 3) {
                if (lan != 1) {
                } else {
                    if (posicion2 == 1) {
                        lblValor3.setText(Integer.toString(1));
                        lbl_padre.setBounds(720, 450, 70, 130);
                        add(lbl_padre);
                        papa = 3;
                        ladoLancha = "arriba";
                    } else {
                        if (posicion2 == 2) {
                            lblValor4.setText(Integer.toString(1));
                            lbl_padre.setBounds(630, 450, 70, 130);
                            add(lbl_padre);
                            papa = 3;
                            ladoLancha = "abajo";
                        } else {
                            if (posicion2 == 3) {
                                lblValor3.setText(Integer.toString(1));
                                lbl_padre.setBounds(720, 450, 70, 130);
                                add(lbl_padre);
                                papa = 3;
                                ladoLancha = "arriba";
                            } else {
                                if (posicion2 == 4) {
                                    lblValor3.setText(Integer.toString(0));
                                    lbl_padre.setBounds(880, 365, 70, 130);
                                    add(lbl_padre);
                                    papa = 2;
                                } else {
                                    if (posicion2 == 5) {
                                        lblValor4.setText(Integer.toString(0));
                                        lbl_padre.setBounds(880, 365, 70, 130);
                                        add(lbl_padre);
                                        papa = 2;
                                    } else {
                                        if (posicion2 == 6) {
                                            lblValor3.setText(Integer.toString(0));
                                            lbl_padre.setBounds(880, 365, 70, 130);
                                            add(lbl_padre);
                                            papa = 2;
                                        } else {
                                            if (posicion2 == 7) {
                                                lblValor4.setText(Integer.toString(0));
                                                lbl_padre.setBounds(880, 365, 70, 130);
                                                add(lbl_padre);
                                                papa = 2;
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
        Fondo.setLocation(0, 0);
        add(Fondo);
    }//GEN-LAST:event_lbl_padreMouseClicked

    private void lbl_hijo1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_hijo1MouseClicked
        valor1 = Integer.parseInt(lblValor1.getText());
        valor2 = Integer.parseInt(lblValor2.getText());
        valor3 = Integer.parseInt(lblValor3.getText());
        valor4 = Integer.parseInt(lblValor4.getText());
        posicion = mv.ValidacionSalida(valor1, valor2, hijo1, ladoLancha);
        posicion2 = mv.ValidacionRegreso(valor3, valor4, hijo1, ladoLancha);
        so.sonidoM();

        if (hijo1 == 0 || hijo1 == 1) {
            if (lan != 0) {
            } else {
                if (posicion == 1) {
                    lblValor1.setText(Integer.toString(1));
                    lbl_hijo1.setBounds(330, 450, 70, 130);
                    add(lbl_hijo1);
                    hijo1 = 1;
                    ladoLancha = "arriba";
                } else {
                    if (posicion == 2) {
                        lblValor2.setText(Integer.toString(1));
                        lbl_hijo1.setBounds(420, 450, 70, 130);
                        add(lbl_hijo1);
                        hijo1 = 1;
                        ladoLancha = "abajo";
                    } else {
                        if (posicion == 3) {
                            lblValor1.setText(Integer.toString(1));
                            lbl_hijo1.setBounds(330, 450, 70, 130);
                            add(lbl_hijo1);
                            hijo1 = 1;
                            ladoLancha = "arriba";
                        } else {
                            if (posicion == 4) {
                                lblValor1.setText(Integer.toString(0));
                                lbl_hijo1.setBounds(110, 365, 70, 130);
                                add(lbl_hijo1);
                                hijo1 = 0;
                            } else {
                                if (posicion == 5) {
                                    lblValor2.setText(Integer.toString(0));
                                    lbl_hijo1.setBounds(110, 365, 70, 130);
                                    add(lbl_hijo1);
                                    hijo1 = 0;
                                } else {
                                    if (posicion == 6) {
                                        lblValor1.setText(Integer.toString(0));
                                        lbl_hijo1.setBounds(110, 365, 70, 130);
                                        add(lbl_hijo1);
                                        hijo1 = 0;
                                    } else {
                                        if (posicion == 7) {
                                            lblValor2.setText(Integer.toString(0));
                                            lbl_hijo1.setBounds(110, 365, 70, 130);
                                            add(lbl_hijo1);
                                            hijo1 = 0;
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        } else {
            if (hijo1 == 2 || hijo1 == 3) {

                if (lan != 1) {

                } else {
                    if (posicion2 == 1) {
                        lblValor3.setText(Integer.toString(1));
                        lbl_hijo1.setBounds(720, 450, 70, 130);
                        add(lbl_hijo1);
                        hijo1 = 3;
                        ladoLancha = "arriba";
                    } else {
                        if (posicion2 == 2) {
                            lblValor4.setText(Integer.toString(1));
                            lbl_hijo1.setBounds(630, 450, 70, 130);
                            add(lbl_hijo1);
                            hijo1 = 3;
                            ladoLancha = "abajo";
                        } else {
                            if (posicion2 == 3) {
                                lblValor3.setText(Integer.toString(1));
                                lbl_hijo1.setBounds(720, 450, 70, 130);
                                add(lbl_hijo1);
                                hijo1 = 3;
                                ladoLancha = "arriba";
                            } else {
                                if (posicion2 == 4) {
                                    lblValor3.setText(Integer.toString(0));
                                    lbl_hijo1.setBounds(980, 365, 70, 130);
                                    add(lbl_hijo1);
                                    hijo1 = 2;
                                } else {
                                    if (posicion2 == 5) {
                                        lblValor4.setText(Integer.toString(0));
                                        lbl_hijo1.setBounds(980, 365, 70, 130);
                                        add(lbl_hijo1);
                                        hijo1 = 2;
                                    } else {
                                        if (posicion2 == 6) {
                                            lblValor3.setText(Integer.toString(0));
                                            lbl_hijo1.setBounds(980, 365, 70, 130);
                                            add(lbl_hijo1);
                                            hijo1 = 2;
                                        } else {
                                            if (posicion2 == 7) {
                                                lblValor4.setText(Integer.toString(0));
                                                lbl_hijo1.setBounds(980, 365, 70, 130);
                                                add(lbl_hijo1);
                                                hijo1 = 2;
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
        Fondo.setLocation(0, 0);
        add(Fondo);
    }//GEN-LAST:event_lbl_hijo1MouseClicked

    private void lbl_hijo2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_hijo2MouseClicked
        valor1 = Integer.parseInt(lblValor1.getText());
        valor2 = Integer.parseInt(lblValor2.getText());
        valor3 = Integer.parseInt(lblValor3.getText());
        valor4 = Integer.parseInt(lblValor4.getText());
        posicion = mv.ValidacionSalida(valor1, valor2, hijo2, ladoLancha);
        posicion2 = mv.ValidacionRegreso(valor3, valor4, hijo2, ladoLancha);
        so.sonidoM();

        if (hijo2 == 0 || hijo2 == 1) {
            if (lan != 0) {
            } else {
                if (posicion == 1) {
                    lblValor1.setText(Integer.toString(1));
                    lbl_hijo2.setBounds(330, 450, 70, 130);
                    add(lbl_hijo2);
                    hijo2 = 1;
                    ladoLancha = "arriba";
                } else {
                    if (posicion == 2) {
                        lblValor2.setText(Integer.toString(1));
                        lbl_hijo2.setBounds(420, 450, 70, 130);
                        add(lbl_hijo2);
                        hijo2 = 1;
                        ladoLancha = "abajo";
                    } else {
                        if (posicion == 3) {
                            lblValor1.setText(Integer.toString(1));
                            lbl_hijo2.setBounds(330, 450, 70, 130);
                            add(lbl_hijo2);
                            hijo2 = 1;
                            ladoLancha = "arriba";
                        } else {
                            if (posicion == 4) {
                                lblValor1.setText(Integer.toString(0));
                                lbl_hijo2.setBounds(20, 365, 70, 130);
                                add(lbl_hijo2);
                                hijo2 = 0;
                            } else {
                                if (posicion == 5) {
                                    lblValor2.setText(Integer.toString(0));
                                    lbl_hijo2.setBounds(20, 365, 70, 130);
                                    add(lbl_hijo2);
                                    hijo2 = 0;
                                } else {
                                    if (posicion == 6) {
                                        lblValor1.setText(Integer.toString(0));
                                        lbl_hijo2.setBounds(20, 365, 70, 130);
                                        add(lbl_hijo2);
                                        hijo2 = 0;
                                    } else {
                                        if (posicion == 7) {
                                            lblValor2.setText(Integer.toString(0));
                                            lbl_hijo2.setBounds(20, 365, 70, 130);
                                            add(lbl_hijo2);
                                            hijo2 = 0;
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        } else {
            if (hijo2 == 2 || hijo2 == 3) {
                if (lan != 1) {
                } else {
                    if (posicion2 == 1) {
                        lblValor3.setText(Integer.toString(1));
                        lbl_hijo2.setBounds(720, 450, 70, 130);
                        add(lbl_hijo2);
                        hijo2 = 3;
                        ladoLancha = "arriba";
                    } else {
                        if (posicion2 == 2) {
                            lblValor4.setText(Integer.toString(1));
                            lbl_hijo2.setBounds(630, 450, 70, 130);
                            add(lbl_hijo2);
                            hijo2 = 3;
                            ladoLancha = "abajo";
                        } else {
                            if (posicion2 == 3) {
                                lblValor3.setText(Integer.toString(1));
                                lbl_hijo2.setBounds(720, 450, 70, 130);
                                add(lbl_hijo2);
                                hijo2 = 3;
                                ladoLancha = "arriba";
                            } else {
                                if (posicion2 == 4) {
                                    lblValor3.setText(Integer.toString(0));
                                    lbl_hijo2.setBounds(1080, 365, 70, 130);
                                    add(lbl_hijo2);
                                    hijo2 = 2;
                                } else {
                                    if (posicion2 == 5) {
                                        lblValor4.setText(Integer.toString(0));
                                        lbl_hijo2.setBounds(1080, 365, 70, 130);
                                        add(lbl_hijo2);
                                        hijo2 = 2;
                                    } else {
                                        if (posicion2 == 6) {
                                            lblValor3.setText(Integer.toString(0));
                                            lbl_hijo2.setBounds(1080, 365, 70, 130);
                                            add(lbl_hijo2);
                                            hijo2 = 2;
                                        } else {
                                            if (posicion2 == 7) {
                                                lblValor4.setText(Integer.toString(0));
                                                lbl_hijo2.setBounds(1080, 365, 70, 130);
                                                add(lbl_hijo2);
                                                hijo2 = 2;
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
        Fondo.setLocation(0, 0);
        add(Fondo);
    }//GEN-LAST:event_lbl_hijo2MouseClicked

    private void lbl_policiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_policiaMouseClicked
        // TODO add your handling code here:
        valor1 = Integer.parseInt(lblValor1.getText());
        valor2 = Integer.parseInt(lblValor2.getText());
        valor3 = Integer.parseInt(lblValor3.getText());
        valor4 = Integer.parseInt(lblValor4.getText());
        posicion = mv.ValidacionSalida(valor1, valor2, policia, ladoLancha);
        posicion2 = mv.ValidacionRegreso(valor3, valor4, policia, ladoLancha);
        so.sonidoM();

        if (policia == 0 || policia == 1) {
            if (lan != 0) {
            } else {
                if (posicion == 1) {
                    lblValor1.setText(Integer.toString(1));
                    lbl_policia.setBounds(330, 450, 70, 130);
                    add(lbl_policia);
                    policia = 1;
                    ladoLancha = "arriba";
                } else {
                    if (posicion == 2) {
                        lblValor2.setText(Integer.toString(1));
                        lbl_policia.setBounds(420, 450, 70, 130);
                        add(lbl_policia);
                        policia = 1;
                        ladoLancha = "abajo";
                    } else {
                        if (posicion == 3) {
                            lblValor1.setText(Integer.toString(1));
                            lbl_policia.setBounds(330, 450, 70, 130);
                            add(lbl_policia);
                            policia = 1;
                            ladoLancha = "arriba";
                        } else {
                            if (posicion == 4) {
                                lblValor1.setText(Integer.toString(0));
                                lbl_policia.setBounds(140, 490, 70, 130);
                                add(lbl_policia);
                                policia = 0;
                            } else {
                                if (posicion == 5) {
                                    lblValor2.setText(Integer.toString(0));
                                    lbl_policia.setBounds(140, 490, 70, 130);
                                    add(lbl_policia);
                                    policia = 0;
                                } else {
                                    if (posicion == 6) {
                                        lblValor1.setText(Integer.toString(0));
                                        lbl_policia.setBounds(140, 490, 70, 130);
                                        add(lbl_policia);
                                        policia = 0;
                                    } else {
                                        if (posicion == 7) {
                                            lblValor2.setText(Integer.toString(0));
                                            lbl_policia.setBounds(140, 490, 70, 130);
                                            add(lbl_policia);
                                            policia = 0;
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        } else {
            if (policia == 2 || policia == 3) {
                if (lan != 1) {
                } else {
                    if (posicion2 == 1) {
                        lblValor3.setText(Integer.toString(1));
                        lbl_policia.setBounds(720, 450, 70, 130);
                        add(lbl_policia);
                        policia = 3;
                        ladoLancha = "arriba";
                    } else {
                        if (posicion2 == 2) {
                            lblValor4.setText(Integer.toString(1));
                            lbl_policia.setBounds(630, 450, 70, 130);
                            add(lbl_policia);
                            policia = 3;
                            ladoLancha = "abajo";
                        } else {
                            if (posicion2 == 3) {
                                lblValor3.setText(Integer.toString(1));
                                lbl_policia.setBounds(720, 450, 70, 130);
                                add(lbl_policia);
                                policia = 3;
                                ladoLancha = "arriba";
                            } else {
                                if (posicion2 == 4) {
                                    lblValor3.setText(Integer.toString(0));
                                    lbl_policia.setBounds(950, 490, 70, 130);
                                    add(lbl_policia);
                                    policia = 2;
                                } else {
                                    if (posicion2 == 5) {
                                        lblValor4.setText(Integer.toString(0));
                                        lbl_policia.setBounds(950, 490, 70, 130);
                                        add(lbl_policia);
                                        policia = 2;
                                    } else {
                                        if (posicion2 == 6) {
                                            lblValor3.setText(Integer.toString(0));
                                            lbl_policia.setBounds(950, 490, 70, 130);
                                            add(lbl_policia);
                                            policia = 2;
                                        } else {
                                            if (posicion2 == 7) {
                                                lblValor4.setText(Integer.toString(0));
                                                lbl_policia.setBounds(950, 490, 70, 130);
                                                add(lbl_policia);
                                                policia = 2;
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
        Fondo.setLocation(0, 0);
        add(Fondo);
    }//GEN-LAST:event_lbl_policiaMouseClicked

    private void lbl_ladronMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_ladronMouseClicked
        valor1 = Integer.parseInt(lblValor1.getText());
        valor2 = Integer.parseInt(lblValor2.getText());
        valor3 = Integer.parseInt(lblValor3.getText());
        valor4 = Integer.parseInt(lblValor4.getText());
        posicion = mv.ValidacionSalida(valor1, valor2, ladron, ladoLancha);
        posicion2 = mv.ValidacionRegreso(valor3, valor4, ladron, ladoLancha);
        so.sonidoM();

        if (ladron == 0 || ladron == 1) {
            if (lan != 0) {
            } else {
                if (posicion == 1) {
                    lblValor1.setText(Integer.toString(1));
                    lbl_ladron.setBounds(330, 450, 70, 130);
                    add(lbl_ladron);
                    ladron = 1;
                    ladoLancha = "arriba";
                } else {
                    if (posicion == 2) {
                        lblValor2.setText(Integer.toString(1));
                        lbl_ladron.setBounds(420, 450, 70, 130);
                        add(lbl_ladron);
                        ladron = 1;
                        ladoLancha = "abajo";
                    } else {
                        if (posicion == 3) {
                            lblValor1.setText(Integer.toString(1));
                            lbl_ladron.setBounds(330, 450, 70, 130);
                            add(lbl_ladron);
                            ladron = 1;
                            ladoLancha = "arriba";
                        } else {
                            if (posicion == 4) {
                                lblValor1.setText(Integer.toString(0));
                                lbl_ladron.setBounds(50, 490, 70, 130);
                                add(lbl_ladron);
                                ladron = 0;
                            } else {
                                if (posicion == 5) {
                                    lblValor2.setText(Integer.toString(0));
                                    lbl_ladron.setBounds(50, 490, 70, 130);
                                    add(lbl_ladron);
                                    ladron = 0;
                                } else {
                                    if (posicion == 6) {
                                        lblValor1.setText(Integer.toString(0));
                                        lbl_ladron.setBounds(50, 490, 70, 130);
                                        add(lbl_ladron);
                                        ladron = 0;
                                    } else {
                                        if (posicion == 7) {
                                            lblValor2.setText(Integer.toString(0));
                                            lbl_ladron.setBounds(50, 490, 70, 130);
                                            add(lbl_ladron);
                                            ladron = 0;
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        } else {
            if (ladron == 2 || ladron == 3) {
                if (lan != 1) {
                } else {
                    if (posicion2 == 1) {
                        lblValor3.setText(Integer.toString(1));
                        lbl_ladron.setBounds(720, 450, 70, 130);
                        add(lbl_ladron);
                        ladron = 3;
                        ladoLancha = "arriba";
                    } else {
                        if (posicion2 == 2) {
                            lblValor4.setText(Integer.toString(1));
                            lbl_ladron.setBounds(630, 450, 70, 130);
                            add(lbl_ladron);
                            ladron = 3;
                            ladoLancha = "abajo";
                        } else {
                            if (posicion2 == 3) {
                                lblValor3.setText(Integer.toString(1));
                                lbl_ladron.setBounds(720, 450, 70, 130);
                                add(lbl_ladron);
                                ladron = 3;
                                ladoLancha = "arriba";
                            } else {
                                if (posicion2 == 4) {
                                    lblValor3.setText(Integer.toString(0));
                                    lbl_ladron.setBounds(1050, 490, 70, 130);
                                    add(lbl_ladron);
                                    ladron = 2;
                                } else {
                                    if (posicion2 == 5) {
                                        lblValor4.setText(Integer.toString(0));
                                        lbl_ladron.setBounds(1050, 490, 70, 130);
                                        add(lbl_ladron);
                                        ladron = 2;
                                    } else {
                                        if (posicion2 == 6) {
                                            lblValor3.setText(Integer.toString(0));
                                            lbl_ladron.setBounds(1050, 490, 70, 130);
                                            add(lbl_ladron);
                                            ladron = 2;
                                        } else {
                                            if (posicion2 == 7) {
                                                lblValor4.setText(Integer.toString(0));
                                                lbl_ladron.setBounds(1050, 490, 70, 130);
                                                add(lbl_ladron);
                                                ladron = 2;
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
        Fondo.setLocation(0, 0);
        add(Fondo);
    }//GEN-LAST:event_lbl_ladronMouseClicked

    private void btn_ReiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ReiniciarActionPerformed
        mama = 0;
        hija1 = 0;
        hija2 = 0;
        papa = 0;
        hijo1 = 0;
        hijo2 = 0;
        policia = 0;
        ladron = 0;
        lan = 0;
        String ladoLancha = "";

        lblValor1.setText("" + 0);
        lblValor2.setText("" + 0);
        lblValor3.setText("" + 0);
        lblValor4.setText("" + 0);
        posicion = 0;
        posicion2 = 0;

        lbl_Movimientos.setText("0");
        lbl_lancha.setBounds(290, 520, 260, 70);
        add(lbl_lancha);

        lbl_madre.setBounds(210, 235, 65, 130);
        add(lbl_madre);

        lbl_hija1.setBounds(110, 235, 65, 130);
        add(lbl_hija1);

        lbl_hija2.setBounds(20, 235, 65, 130);
        add(lbl_hija2);

        lbl_padre.setBounds(210, 365, 65, 130);
        add(lbl_padre);

        lbl_hijo1.setBounds(110, 365, 65, 130);
        add(lbl_hijo1);
        hijo1 = 0;

        lbl_hijo2.setBounds(20, 365, 65, 130);
        add(lbl_hijo2);

        lbl_policia.setBounds(140, 490, 65, 130);
        add(lbl_policia);

        lbl_ladron.setBounds(50, 490, 70, 120);
        add(lbl_ladron);

        Fondo.setLocation(0, 0);
        add(Fondo);

        btn_Avanzar.setEnabled(true);
        btn_regresar.setEnabled(false);
    }//GEN-LAST:event_btn_ReiniciarActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        Menu m = new Menu();
        m.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void btnInstruccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInstruccionesActionPerformed
        so.Iistrucciones();
    }//GEN-LAST:event_btnInstruccionesActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        so.IistruccionesStop();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Juego().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JButton btnInstrucciones;
    private javax.swing.JButton btn_Avanzar;
    private javax.swing.JButton btn_Reiniciar;
    private javax.swing.JButton btn_regresar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JLabel lblInstrucciones;
    private javax.swing.JLabel lblValor1;
    private javax.swing.JLabel lblValor2;
    private javax.swing.JLabel lblValor3;
    private javax.swing.JLabel lblValor4;
    private javax.swing.JLabel lbl_Movimientos;
    private javax.swing.JLabel lbl_hija1;
    private javax.swing.JLabel lbl_hija2;
    private javax.swing.JLabel lbl_hijo1;
    private javax.swing.JLabel lbl_hijo2;
    private javax.swing.JLabel lbl_ladron;
    private javax.swing.JLabel lbl_lancha;
    private javax.swing.JLabel lbl_madre;
    private javax.swing.JLabel lbl_padre;
    private javax.swing.JLabel lbl_policia;
    // End of variables declaration//GEN-END:variables
}
