
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package juegocurzarrio;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author Pablo
 */
public class Menu extends javax.swing.JFrame {

     private Timer Timer;
     Juego in = new Juego();
     Sonido so = new Sonido();
    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        setBounds(100, 0, 1160, 627);
        Carga.setVisible(false);
        //so.sonidoI();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Inicio = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnComenzar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        Carga = new javax.swing.JPanel();
        progressbar = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        Inicio.setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        jPanel1.setLayout(null);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("                  Problema “Cruzar el rio”.\n \nUn grupo de personas y sus animales necesitan pasar a la \notra orilla de un rio utilizando una lancha que solamente \npuede transportar a dos personas. \n\nTodas las personas deben cruzar el rio.  \n\n                         Personajes:  \n                  En el grupo se encuentran:  \n                         -Un policía.  \n                         -Un ladrón.  \n             -Una granjera con sus dos animales. \n             -Un granjero con sus dos animales.   \n\n                        Condiciones: \nSolamente el policía, el granjero y la granjera saben \noperar la lancha para transportar a las personas al otro \nlado del rio. El granjero no puede permanecer o estar \ncon los animales de la granjera sin que esté presente la \ngranjera. La granjera no puede permanecer o estar con \nlos animales del granjero sí que esté presente el granjero.\nEl ladrón no puede permanecer o estar con ninguna otra \npersona o animal sin la presencia del policía.");
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(30, 30, 500, 400);

        Inicio.add(jPanel1);
        jPanel1.setBounds(50, 100, 560, 460);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/au.png"))); // NOI18N
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        Inicio.add(jButton2);
        jButton2.setBounds(200, 30, 50, 40);

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botonSalir1.png"))); // NOI18N
        btnSalir.setBorderPainted(false);
        btnSalir.setContentAreaFilled(false);
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSalir.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botonSalir2.png"))); // NOI18N
        btnSalir.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botonSalir1.png"))); // NOI18N
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        Inicio.add(btnSalir);
        btnSalir.setBounds(760, 419, 300, 90);

        btnComenzar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botonInicio1.png"))); // NOI18N
        btnComenzar.setBorderPainted(false);
        btnComenzar.setContentAreaFilled(false);
        btnComenzar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnComenzar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnComenzar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botonInicio2.png"))); // NOI18N
        btnComenzar.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botonInicio1.png"))); // NOI18N
        btnComenzar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComenzarActionPerformed(evt);
            }
        });
        Inicio.add(btnComenzar);
        btnComenzar.setBounds(750, 250, 300, 90);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ICONO-SONIDO.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        Inicio.add(jButton1);
        jButton1.setBounds(130, 30, 50, 40);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondoIni.jpg"))); // NOI18N
        jLabel4.setAlignmentY(0.0F);
        Inicio.add(jLabel4);
        jLabel4.setBounds(0, 0, 1160, 680);

        getContentPane().add(Inicio);
        Inicio.setBounds(0, 0, 1160, 630);

        Carga.setLayout(null);

        progressbar.setForeground(new java.awt.Color(102, 204, 0));
        progressbar.setStringPainted(true);
        Carga.add(progressbar);
        progressbar.setBounds(410, 320, 380, 78);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cargando (2).gif"))); // NOI18N
        Carga.add(jLabel1);
        jLabel1.setBounds(580, 230, 50, 50);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Fondon.png"))); // NOI18N
        Carga.add(jLabel3);
        jLabel3.setBounds(0, 0, 1170, 640);

        getContentPane().add(Carga);
        Carga.setBounds(0, 0, 1170, 630);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        so.sonidoB();
        int ax = JOptionPane.showConfirmDialog(null, "De verdad deseas salir de la aplicacion?");
        if(ax == JOptionPane.YES_OPTION){
            JOptionPane.showMessageDialog(null, "Regresa pronto!!","Exit",JOptionPane.INFORMATION_MESSAGE);
            System.exit(0);
        }else if(ax == JOptionPane.NO_OPTION){
            JOptionPane.showMessageDialog(null, "Gracias por no salir.");
        }
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnComenzarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComenzarActionPerformed
        // TODO add your handling code here:
        so.sonidoB();
        Timer=new Timer(100,new progreso());
        Timer.start();
        Inicio.setVisible(false);
        Carga.setVisible(true);
        Hilo h1 = new Hilo(progressbar);
        h1.start();
    }//GEN-LAST:event_btnComenzarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        so.Iistrucciones();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        so.IistruccionesStop();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Carga;
    private javax.swing.JPanel Inicio;
    private javax.swing.JButton btnComenzar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JProgressBar progressbar;
    // End of variables declaration//GEN-END:variables


    public class progreso implements ActionListener{
    public void actionPerformed(ActionEvent evt){
        int n=progressbar.getValue();
        if(n<100){
            n++;
            progressbar.setValue(n);
        }else{
            Timer.stop();
            in.setVisible(true);
            dispose();
        }
    }
}
    
}
